debug: false
secret: 8A4N3xxxxxxxxxxxxxxm66nt
invitation: false
moreuRoot: ../moreu-front/dist # 前端目录，如果定义则优先使用该目录下的前端文件，否则使用内置的前端页面

#email:
#  host: smtpdm.aliyun.com:25
#  sender: no-reply@saltbo.fun
#  username: Moreu
#  password: mG0xxxxxxWh9

database:
  driver: mysql
  dsn: root:admin@(localhost:3306)/zpan?charset=utf8&parseTime=True&loc=Local

routers:
  - pattern: /moreu
    upstream:
      address: http://localhost:8081
  - pattern: /api/moreu
    upstream:
      address: http://localhost:8081

  - pattern: /
    upstream:
      address: http://localhost:8083
